version: '3'
services:
  web001:
    build:
      context: .
      dockerfile: Dockerfile-agent
    command: /sbin/init
    privileged: true
    hostname: web001
    ports:
      - '8080:80'
    links:
      - pmaster:pmaster

  pmaster:
    build:
      context: .
      dockerfile: Dockerfile-master
    command: /sbin/init
    privileged: true
    hostname: pmaster
    volumes:
      - ./manifests_pmaster:/etc/puppetlabs/code/environments/development/manifests
      - ./environment.conf:/etc/puppetlabs/code/environments/development/environment.conf
