FROM asuforce/puppet
MAINTAINER Shun Nishitsuji <shun.nishitsuji@pepabo.com>

RUN apt-get update

RUN mkdir /etc/puppet
ADD . /etc/puppet

WORKDIR /etc/puppet
RUN bundle install
RUN bundle exec librarian-puppet install
